/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/create-neighborhood': RouteRecordInfo<'/create-neighborhood', '/create-neighborhood', Record<never, never>, Record<never, never>>,
    '/garage/[id]': RouteRecordInfo<'/garage/[id]', '/garage/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/host/[garageId]': RouteRecordInfo<'/host/[garageId]', '/host/:garageId', { garageId: ParamValue<true> }, { garageId: ParamValue<false> }>,
    '/join/[token]': RouteRecordInfo<'/join/[token]', '/join/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    '/ticket/[ticketId]': RouteRecordInfo<'/ticket/[ticketId]', '/ticket/:ticketId', { ticketId: ParamValue<true> }, { ticketId: ParamValue<false> }>,
  }
}
